"""Property-based tests for guardrails coverage on every model call.

Tests verify that Bedrock Guardrails scanning is applied in BOTH the INPUT
and OUTPUT directions on every model invocation path through the agent graph.

**Validates: Requirements 8.1**

Properties tested:
- Property 7: Guardrails on Every Model Call — input AND output scanning
  on every model invocation.

Architecture context:
- Model-calling nodes: intent_classify, sql_generate, self_correct, disambiguate
- Input scanning: scan_input() from output_scan module (scans user message + context)
- Output scanning: output_scan graph node (scans model results through Bedrock Guardrails)
- The graph structure ensures output_scan is on every path that reaches format_respond
- Input scanning must be applied before/during model calls
"""

from __future__ import annotations

from typing import Any
from unittest.mock import MagicMock, patch

from hypothesis import given, assume, settings, HealthCheck
from hypothesis import strategies as st

from chatbot.agent.graph import (
    AgentGraph,
    GraphState,
    after_disambiguate,
    after_validate_sql,
    should_disambiguate,
    should_self_correct,
)
from chatbot.agent.nodes.output_scan import (
    scan_input,
    scan_output,
    output_scan,
    GuardrailScanResult,
    GUARDRAILS_CONFIG,
    GUARDRAIL_ID,
    GUARDRAIL_VERSION,
)


# ─── Hypothesis Strategies ────────────────────────────────────────────────────

# User messages of varying length and content
user_message_strategy = st.text(
    min_size=1,
    max_size=500,
    alphabet=st.characters(categories=("L", "N", "P", "Z")),
)

# SQL queries generated by the model
sql_strategy = st.one_of(
    st.just("SELECT id, name FROM users WHERE date = '2024-01-01'"),
    st.just("SELECT count(*) FROM orders GROUP BY region"),
    st.text(min_size=5, max_size=200, alphabet=st.characters(categories=("L", "N", "P", "Z"))),
)

# User roles from the system
role_strategy = st.sampled_from(["analyst", "manager", "viewer", "compliance_officer"])

# Departments
department_strategy = st.sampled_from(["finance", "analytics", "hr", "engineering"])

# Guardrail scan directions
scan_direction_strategy = st.sampled_from(["INPUT", "OUTPUT"])


@st.composite
def user_claims_strategy(draw) -> dict[str, Any]:
    """Generate valid user claims for testing."""
    return {
        "sub": draw(st.text(min_size=5, max_size=30, alphabet="abcdefghijklmnop0123456789-")),
        "role": draw(role_strategy),
        "department": draw(department_strategy),
        "data_classification_tier": draw(st.sampled_from(["internal", "confidential"])),
        "groups": draw(st.lists(st.sampled_from(["elevated_cost", "analysts", "managers"]), max_size=3)),
    }


@st.composite
def model_output_content_strategy(draw) -> str:
    """Generate model output content that might contain PII or sensitive data."""
    base = draw(st.sampled_from([
        "The total revenue was $1.2M across 5 regions.",
        "Query returned 150 rows from the orders table.",
        "John Smith (john@example.com) placed 10 orders.",
        "Account 1234-5678-9012-3456 has a balance of $50,000.",
        "SELECT completed successfully. No matching rows found.",
    ]))
    return base


@st.composite
def graph_state_with_model_output(draw) -> GraphState:
    """Generate a GraphState representing post-model-call state with results."""
    user_claims = draw(user_claims_strategy())
    return {
        "user_message": draw(user_message_strategy),
        "user_claims": user_claims,
        "query_results": {
            "columns": ["id", "name", "amount"],
            "rows": [{"id": 1, "name": draw(st.text(min_size=1, max_size=50)), "amount": draw(st.integers(min_value=0, max_value=100000))}],
            "row_count": 1,
            "bytes_scanned": draw(st.integers(min_value=100, max_value=10000000)),
        },
        "guardrails_findings": draw(st.just([]) | st.just(["PII:EMAIL:ANONYMIZED"])),
    }


# ─── Property 7: Guardrails on Every Model Call ──────────────────────────────


class TestGuardrailsOnEveryModelCall:
    """Property 7: Guardrails on Every Model Call.

    **Validates: Requirements 8.1**

    Every model invocation in the agent graph must have BOTH input scanning
    and output scanning applied through Bedrock Guardrails. No model call
    shall bypass scanning in either direction.

    The architecture ensures this through:
    1. Input scanning: scan_input() is available and must be called before/during
       every model invocation (intent_classify, sql_generate, self_correct, disambiguate)
    2. Output scanning: the output_scan node is on every graph path that processes
       model results before reaching format_respond
    """

    def test_graph_output_scan_on_every_path_to_end(self):
        """The output_scan node is on every path from tool_call to END.

        **Validates: Requirements 8.1**

        The graph structure guarantees that output_scan is always executed
        before format_respond, ensuring output scanning cannot be bypassed.
        """
        agent_graph = AgentGraph()
        graph = agent_graph.build_graph()

        # Verify output_scan node exists in the graph
        assert "output_scan" in graph.nodes, (
            "output_scan node missing from graph — output guardrails scanning not integrated"
        )

        # Verify output_scan has a direct edge to format_respond
        # This confirms output_scan is the last processing step before final response
        assert ("output_scan", "format_respond") in graph.edges, (
            "output_scan must have a direct edge to format_respond — "
            "ensures no path bypasses output scanning before response"
        )

        # Verify tool_call routes through should_self_correct which leads to output_scan
        # The only routes from tool_call are: self_correct or output_scan
        # Both eventually lead through output_scan before format_respond

    def test_graph_output_scan_is_only_path_to_format_respond_from_tool_call(self):
        """The only path from tool_call to format_respond goes through output_scan.

        **Validates: Requirements 8.1**

        There is no edge from tool_call directly to format_respond. The
        should_self_correct conditional edge only routes to either:
        - self_correct (loops back to validate_sql)
        - output_scan (which then goes to format_respond)

        This ensures model output is ALWAYS scanned.
        """
        agent_graph = AgentGraph()
        graph = agent_graph.build_graph()

        # Verify there is NO direct edge from tool_call to format_respond
        assert ("tool_call", "format_respond") not in graph.edges, (
            "Direct edge from tool_call to format_respond detected! "
            "This bypasses output guardrails scanning."
        )

        # Verify there is NO direct edge from tool_call to END
        assert ("tool_call", "__end__") not in graph.edges, (
            "Direct edge from tool_call to END detected! "
            "This bypasses output guardrails scanning."
        )

    @given(
        has_error=st.booleans(),
        attempts=st.integers(min_value=0, max_value=100),
    )
    @settings(max_examples=300)
    def test_should_self_correct_always_leads_to_output_scan_eventually(
        self, has_error: bool, attempts: int
    ):
        """should_self_correct conditional edge ensures output_scan is always reached.

        **Validates: Requirements 8.1**

        The should_self_correct function routes to either:
        - "self_correct" (which loops back to validate_sql and eventually reaches tool_call again)
        - "output_scan" (direct path to output scanning)

        In ALL cases, the path eventually reaches output_scan because:
        - self_correction is bounded (max 2), so eventually the loop terminates
        - When the loop terminates (attempts >= 2), it routes to output_scan
        - When there's no error, it routes directly to output_scan
        """
        state: GraphState = {
            "sql_error": "some error" if has_error else None,
            "self_correction_attempts": attempts,
        }
        result = should_self_correct(state)

        # Result is always either "self_correct" or "output_scan"
        assert result in ("self_correct", "output_scan"), (
            f"Unexpected routing result: {result}. "
            f"Expected 'self_correct' or 'output_scan'."
        )

        # When attempts >= max, MUST route to output_scan (guaranteeing scanning)
        if attempts >= AgentGraph.MAX_SELF_CORRECTION_RETRIES:
            assert result == "output_scan", (
                f"At max attempts ({attempts}), must route to output_scan for "
                f"guardrails coverage, but got '{result}'"
            )

        # When no error, MUST route to output_scan
        if not has_error:
            assert result == "output_scan", (
                f"No error present, must route to output_scan for "
                f"guardrails coverage, but got '{result}'"
            )

    @given(content=user_message_strategy)
    @settings(max_examples=200, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_scan_input_always_invokes_guardrails_api(self, content: str):
        """scan_input always calls the ApplyGuardrail API in INPUT direction.

        **Validates: Requirements 8.1**

        For any non-empty input content, the scan_input function MUST
        invoke the Bedrock ApplyGuardrail API with source="INPUT" and
        all content filters at HIGH threshold.
        """
        assume(len(content.strip()) > 0)

        mock_client = MagicMock()
        mock_client.apply_guardrail.return_value = {
            "action": "NONE",
            "outputs": [{"text": content}],
            "assessments": [],
        }

        with patch(
            "chatbot.agent.nodes.output_scan._get_client",
            return_value=mock_client,
        ):
            result = scan_input(content)

            # Verify ApplyGuardrail was called
            mock_client.apply_guardrail.assert_called_once()

            # Verify INPUT direction
            call_kwargs = mock_client.apply_guardrail.call_args[1]
            assert call_kwargs["source"] == "INPUT", (
                f"scan_input must use source='INPUT', got '{call_kwargs['source']}'"
            )

            # Verify correct guardrail ID
            assert call_kwargs["guardrailIdentifier"] == GUARDRAIL_ID

            # Verify content was passed for scanning
            content_payload = call_kwargs["content"]
            assert len(content_payload) > 0, "Content payload must not be empty"
            assert content_payload[0]["text"]["text"] == content

    @given(content=model_output_content_strategy())
    @settings(max_examples=200, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_scan_output_always_invokes_guardrails_api(self, content: str):
        """scan_output always calls the ApplyGuardrail API in OUTPUT direction.

        **Validates: Requirements 8.1**

        For any non-empty output content, the scan_output function MUST
        invoke the Bedrock ApplyGuardrail API with source="OUTPUT" and
        all content filters at HIGH threshold.
        """
        assume(len(content.strip()) > 0)

        mock_client = MagicMock()
        mock_client.apply_guardrail.return_value = {
            "action": "NONE",
            "outputs": [{"text": content}],
            "assessments": [],
        }

        with patch(
            "chatbot.agent.nodes.output_scan._get_client",
            return_value=mock_client,
        ):
            result = scan_output(content)

            # Verify ApplyGuardrail was called
            mock_client.apply_guardrail.assert_called_once()

            # Verify OUTPUT direction
            call_kwargs = mock_client.apply_guardrail.call_args[1]
            assert call_kwargs["source"] == "OUTPUT", (
                f"scan_output must use source='OUTPUT', got '{call_kwargs['source']}'"
            )

            # Verify correct guardrail ID
            assert call_kwargs["guardrailIdentifier"] == GUARDRAIL_ID

    @given(state=graph_state_with_model_output())
    @settings(max_examples=200, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_output_scan_node_always_scans_when_results_present(
        self, state: GraphState
    ):
        """The output_scan node always invokes guardrails when query_results exist.

        **Validates: Requirements 8.1**

        When the graph state contains query_results (model output), the
        output_scan node MUST call scan_output to apply guardrails scanning
        in the OUTPUT direction. No model output bypasses scanning.
        """
        query_results = state.get("query_results")
        assume(query_results is not None)

        mock_client = MagicMock()
        mock_client.apply_guardrail.return_value = {
            "action": "NONE",
            "outputs": [],
            "assessments": [],
        }

        with patch(
            "chatbot.agent.nodes.output_scan._get_client",
            return_value=mock_client,
        ):
            result = output_scan(state)

            # Guardrails API must have been called for OUTPUT scanning
            mock_client.apply_guardrail.assert_called_once()
            call_kwargs = mock_client.apply_guardrail.call_args[1]

            assert call_kwargs["source"] == "OUTPUT", (
                f"output_scan node must scan in OUTPUT direction, "
                f"got '{call_kwargs['source']}'"
            )

    @given(
        user_message=user_message_strategy,
        additional_context=st.one_of(st.none(), sql_strategy),
    )
    @settings(max_examples=200, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_scan_input_combines_message_and_context(
        self, user_message: str, additional_context: str | None
    ):
        """scan_input scans both user message and additional context (e.g., SQL).

        **Validates: Requirements 8.1**

        Input scanning must cover the full input surface: user message AND
        any generated SQL or additional context that is passed to the model.
        This ensures prompt injection detection covers all input vectors.
        """
        assume(len(user_message.strip()) > 0)

        mock_client = MagicMock()
        mock_client.apply_guardrail.return_value = {
            "action": "NONE",
            "outputs": [{"text": user_message}],
            "assessments": [],
        }

        with patch(
            "chatbot.agent.nodes.output_scan._get_client",
            return_value=mock_client,
        ):
            result = scan_input(user_message, additional_context=additional_context)

            # Verify the scan was performed
            mock_client.apply_guardrail.assert_called_once()
            call_kwargs = mock_client.apply_guardrail.call_args[1]

            # Verify the content includes the user message
            scanned_text = call_kwargs["content"][0]["text"]["text"]
            assert user_message in scanned_text, (
                "User message must be included in input scan content"
            )

            # If additional context provided, it must also be included
            if additional_context:
                assert additional_context in scanned_text, (
                    "Additional context (e.g., generated SQL) must be included "
                    "in input scan to detect injection in all input vectors"
                )

    @given(
        user_message=user_message_strategy,
        user_claims=user_claims_strategy(),
    )
    @settings(max_examples=200, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_scan_input_blocks_on_guardrails_unavailability(
        self, user_message: str, user_claims: dict[str, Any]
    ):
        """scan_input raises RuntimeError when guardrails are unavailable (fail-closed).

        **Validates: Requirements 8.1**

        When the Bedrock Guardrails service is unavailable, scan_input MUST
        raise a RuntimeError to signal fail-closed behavior. The calling node
        must NOT proceed with the model call when scanning fails.
        """
        assume(len(user_message.strip()) > 0)

        mock_client = MagicMock()
        mock_client.apply_guardrail.side_effect = Exception("Service unavailable")

        with patch(
            "chatbot.agent.nodes.output_scan._get_client",
            return_value=mock_client,
        ):
            try:
                scan_input(user_message)
                # If we get here without exception, fail-closed is not enforced
                assert False, (
                    "scan_input must raise RuntimeError when guardrails are "
                    "unavailable to enforce fail-closed behavior"
                )
            except RuntimeError as e:
                # Expected: fail-closed behavior
                assert "unavailable" in str(e).lower() or "blocking" in str(e).lower(), (
                    f"RuntimeError message should indicate fail-closed: {e}"
                )

    @given(state=graph_state_with_model_output())
    @settings(max_examples=200, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_output_scan_node_fails_closed_on_unavailability(
        self, state: GraphState
    ):
        """output_scan node blocks the response when guardrails are unavailable.

        **Validates: Requirements 8.1**

        When the Bedrock Guardrails service is unavailable during output scanning,
        the output_scan node MUST fail-closed: set query_results to None and
        return an error message. Model output must NEVER reach the user unscanned.
        """
        query_results = state.get("query_results")
        assume(query_results is not None)

        mock_client = MagicMock()
        mock_client.apply_guardrail.side_effect = Exception("Service timeout")

        with patch(
            "chatbot.agent.nodes.output_scan._get_client",
            return_value=mock_client,
        ):
            result = output_scan(state)

            # Fail-closed: query_results must be cleared
            assert result.get("query_results") is None, (
                "output_scan must clear query_results on guardrails failure "
                "(fail-closed behavior). Unscanned model output must not reach user."
            )

            # An error message must be present
            assert result.get("error") is not None, (
                "output_scan must set an error message when failing closed"
            )

    def test_guardrails_config_all_filters_high(self):
        """Guardrails configuration has all content filters at HIGH threshold.

        **Validates: Requirements 8.1**

        The STANDARD tier configuration must set ALL content filter categories
        (hate, violence, sexual, insults, misconduct, prompt attacks) to HIGH.
        No filter may be set below HIGH.
        """
        config = GUARDRAILS_CONFIG

        assert config.tier == "STANDARD", (
            f"Expected STANDARD tier, got '{config.tier}'"
        )
        assert config.hate_threshold.value == "HIGH", (
            f"hate threshold must be HIGH, got '{config.hate_threshold.value}'"
        )
        assert config.violence_threshold.value == "HIGH", (
            f"violence threshold must be HIGH, got '{config.violence_threshold.value}'"
        )
        assert config.sexual_threshold.value == "HIGH", (
            f"sexual threshold must be HIGH, got '{config.sexual_threshold.value}'"
        )
        assert config.insults_threshold.value == "HIGH", (
            f"insults threshold must be HIGH, got '{config.insults_threshold.value}'"
        )
        assert config.misconduct_threshold.value == "HIGH", (
            f"misconduct threshold must be HIGH, got '{config.misconduct_threshold.value}'"
        )
        assert config.prompt_attack_threshold.value == "HIGH", (
            f"prompt_attack threshold must be HIGH, got '{config.prompt_attack_threshold.value}'"
        )

    def test_guardrails_config_pii_anonymize(self):
        """Guardrails PII action is set to ANONYMIZE.

        **Validates: Requirements 8.1**

        PII entities must be anonymized (not just detected) to ensure
        sensitive data never reaches the user unredacted by default.
        """
        config = GUARDRAILS_CONFIG
        assert config.pii_action == "ANONYMIZE", (
            f"PII action must be 'ANONYMIZE', got '{config.pii_action}'"
        )

    def test_model_calling_nodes_identified_in_graph(self):
        """All model-calling nodes are present in the agent graph.

        **Validates: Requirements 8.1**

        The nodes that invoke Bedrock models (and thus require guardrails
        scanning) must all be registered in the agent graph:
        - intent_classify (Claude Haiku)
        - sql_generate (Claude Sonnet)
        - self_correct (Claude Sonnet)
        - disambiguate (Claude Haiku)
        """
        agent_graph = AgentGraph()
        graph = agent_graph.build_graph()

        model_calling_nodes = [
            "intent_classify",
            "sql_generate",
            "self_correct",
            "disambiguate",
        ]

        for node in model_calling_nodes:
            assert node in graph.nodes, (
                f"Model-calling node '{node}' must be in the graph for "
                f"guardrails coverage verification"
            )

    def test_output_scan_node_reachable_from_all_model_output_paths(self):
        """output_scan is reachable from every path that produces model output.

        **Validates: Requirements 8.1**

        The graph structure ensures that any path involving tool_call
        (which returns model/query results) must pass through output_scan
        before reaching format_respond. This guarantees OUTPUT direction
        scanning on every model output path.

        Graph topology ensures:
        - tool_call → should_self_correct → output_scan → format_respond
        - tool_call → should_self_correct → self_correct → validate_sql → ... → output_scan
        """
        agent_graph = AgentGraph()
        graph = agent_graph.build_graph()

        # output_scan is the ONLY predecessor of format_respond via direct edges
        # (other than conditional edges from disambiguation giving up)
        assert ("output_scan", "format_respond") in graph.edges

        # format_respond is the ONLY node with an edge to END
        end_edges = [(src, dst) for src, dst in graph.edges if dst == "__end__"]
        assert any(src == "format_respond" for src, dst in end_edges), (
            "format_respond must be the node that leads to END"
        )

    @given(
        direction=scan_direction_strategy,
        content=user_message_strategy,
    )
    @settings(max_examples=200, suppress_health_check=[HealthCheck.function_scoped_fixture])
    def test_guardrails_scan_covers_both_directions(
        self, direction: str, content: str
    ):
        """Guardrails scanning functions exist for both INPUT and OUTPUT directions.

        **Validates: Requirements 8.1**

        The system provides scan_input (INPUT direction) and scan_output
        (OUTPUT direction) to cover both sides of every model invocation.
        Both directions must use the same guardrail configuration (STANDARD
        tier, all filters HIGH).
        """
        assume(len(content.strip()) > 0)

        mock_client = MagicMock()
        mock_client.apply_guardrail.return_value = {
            "action": "NONE",
            "outputs": [{"text": content}],
            "assessments": [],
        }

        with patch(
            "chatbot.agent.nodes.output_scan._get_client",
            return_value=mock_client,
        ):
            if direction == "INPUT":
                scan_input(content)
            else:
                scan_output(content)

            # Verify the correct direction was used
            call_kwargs = mock_client.apply_guardrail.call_args[1]
            assert call_kwargs["source"] == direction, (
                f"Expected scan direction '{direction}', "
                f"got '{call_kwargs['source']}'"
            )

            # Both directions use the same guardrail ID and version
            assert call_kwargs["guardrailIdentifier"] == GUARDRAIL_ID
            assert call_kwargs["guardrailVersion"] == GUARDRAIL_VERSION
